# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='states',
            field=models.CharField(choices=[('STARTED', 'started'), ('PENDING', 'pending')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='task_environment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
