# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20180712_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskrun',
            old_name='states',
            new_name='status',
        ),
    ]
