# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_auto_20180712_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='task_id',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
